### PR TITLE
Sanitize tips

### PR DESCRIPTION
**Pull request by micuffaro**
Addresses https://github.com/exercism/exalysis/issues/102

I've got a failing CI which I will have to take a look at later on...

### CODE REVIEW

**Review by tehsphinx — APPROVED** [review]
LGTM

**Comment by bitfield** [comment]
What do you mean by "sanitize", @micuffaro? I see you've changed the link to one of the videos, but I don't understand the other changes.

**Comment by micuffaro** [comment]
My apologies for not being clear there @bitfield!

Yes indeed I went through all tips, updated (mostly youtube) links where relevant, and did minor grammatical or formatting changes.
One tip I deleted altogether: `gtpl/tips/gophervids.md `;
I could not find the original resource at all, or any other which would be an adequate substitute (googling for "gophervids" now returns other content completely unrelated to Go).
In doing so I realized we are using `go-bindata` to embed the markdown files in the package, so I re-ran it, and cleaned up as well my go.mod.

Let me know if you think any of these changes are out of line or unnecessary.

**Comment by bitfield** [comment]
Fine! Well, once you've fixed the build errors, I think we'll be all good!

**Comment by micuffaro** [comment]
@tehsphinx , I cannot really figure out what is wrong with the CI.
Can you help me understand what I am doing wrong?

**Comment by tehsphinx** [comment]
@micuffaro: I'd try what it says: Use `go get` instead of `go install` to install golangci-lint.

Another option would be to change to the `golangci/golangci-lint` docker image to run the linters.

**Comment by micuffaro** [comment]
thanks @tehsphinx , I think we are ready :)

**Pull request merged**
